export const colors = {
  background: '#F7FAFB',
  surface: '#FFFFFF',
  surfaceDim: '#EEF4F6',
  surfaceBright: '#FFFFFF',
  surfaceContainerLowest: '#FFFFFF',
  surfaceContainerLow: '#F1F7F9',
  surfaceContainer: '#EEF4F6',
  surfaceContainerHigh: '#E7EFF2',
  surfaceContainerHighest: '#DFE9ED',
  surfaceVariant: '#E4EDF1',
  surfaceTint: '#1CA7C4',
  onSurface: '#0F2A38',
  onSurfaceVariant: '#54707C',
  onBackground: '#0F2A38',
  inverseSurface: '#0B2A38',
  inverseOnSurface: '#F1F7F9',
  outline: '#7C95A0',
  outlineVariant: '#E4EDF1',
  primary: '#1CA7C4',
  onPrimary: '#FFFFFF',
  primaryContainer: '#D6EEF4',
  onPrimaryContainer: '#0E7FA8',
  primaryFixed: '#1CA7C4',
  primaryFixedDim: '#0E7FA8',
  onPrimaryFixed: '#04313F',
  onPrimaryFixedVariant: '#0E7FA8',
  inversePrimary: '#7FD7E6',
  secondary: '#17B5AE',
  onSecondary: '#FFFFFF',
  secondaryContainer: '#D2F1EE',
  onSecondaryContainer: '#0C6A65',
  secondaryFixed: '#D2F1EE',
  secondaryFixedDim: '#17B5AE',
  onSecondaryFixed: '#04302D',
  onSecondaryFixedVariant: '#0C6A65',
  tertiary: '#F2A65A',
  onTertiary: '#FFFFFF',
  tertiaryContainer: '#FCE5CC',
  onTertiaryContainer: '#8A4B12',
  tertiaryFixed: '#FCE5CC',
  tertiaryFixedDim: '#F2A65A',
  onTertiaryFixed: '#3D2207',
  onTertiaryFixedVariant: '#8A4B12',
  error: '#BA1A1A',
  onError: '#FFFFFF',
  errorContainer: '#FFDAD6',
  onErrorContainer: '#93000a',
} as const

export const typography = {
  displayLg: { fontFamily: 'Space Grotesk', fontSize: '72px', fontWeight: '700', lineHeight: '1.1', letterSpacing: '-0.02em' },
  displayLgMobile: { fontFamily: 'Space Grotesk', fontSize: '40px', fontWeight: '700', lineHeight: '1.2' },
  headlineMd: { fontFamily: 'Space Grotesk', fontSize: '32px', fontWeight: '600', lineHeight: '1.3' },
  subheadingPremium: { fontFamily: 'Newsreader', fontSize: '24px', fontWeight: '400', lineHeight: '1.4', fontStyle: 'italic' },
  bodyLg: { fontFamily: 'Hanken Grotesk', fontSize: '18px', fontWeight: '400', lineHeight: '1.6' },
  bodySm: { fontFamily: 'Hanken Grotesk', fontSize: '14px', fontWeight: '400', lineHeight: '1.5' },
  labelCaps: { fontFamily: 'Hanken Grotesk', fontSize: '12px', fontWeight: '600', lineHeight: '1', letterSpacing: '0.1em' },
} as const

export const spacing = {
  unit: '8px',
  gutter: '24px',
  containerMax: '1280px',
  marginDesktop: '80px',
  marginMobile: '20px',
  sectionGap: '120px',
} as const

export const borderRadius = {
  sm: '0.25rem',
  DEFAULT: '0.5rem',
  md: '0.75rem',
  lg: '1rem',
  xl: '1.5rem',
  full: '9999px',
} as const
